arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin
  position_only_ik: True
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 10
  kinematics_solver_attempts: 10
  solve_type: Distance